sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t frontend .
scripts:
  - docker run  -e CI=true frontend npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "test-docker"
  env: "Testdocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-876515858155"
  bucket_path: "test-docker"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
